version: '3'

volumes:
  postgres:
  app:
  protoc:

services:
  postgres:
    container_name: homedog.db  # host
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  homedog:
    container_name: homedog
    image: homedog
    build: platforms/Go
    depends_on:
      - postgres
    volumes:
      - ./config:/app/config
      - ./platforms/Go/src:/app/src
    links:
      - postgres:db.homedog
    env_file:
      - .env
    restart: always
